# -*- coding: utf-8 -*-
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Adding field 'TipoUsuario.nombre'
        db.add_column(u'controles_tipousuario', 'nombre',
                      self.gf('django.db.models.fields.CharField')(default='El mismo', max_length=40),
                      keep_default=False)


    def backwards(self, orm):
        # Deleting field 'TipoUsuario.nombre'
        db.delete_column(u'controles_tipousuario', 'nombre')


    models = {
        u'auth.group': {
            'Meta': {'object_name': 'Group'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '80'}),
            'permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'})
        },
        u'auth.permission': {
            'Meta': {'ordering': "(u'content_type__app_label', u'content_type__model', u'codename')", 'unique_together': "((u'content_type', u'codename'),)", 'object_name': 'Permission'},
            'codename': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['contenttypes.ContentType']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        },
        u'auth.user': {
            'Meta': {'object_name': 'User'},
            'date_joined': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'email': ('django.db.models.fields.EmailField', [], {'max_length': '75', 'blank': 'True'}),
            'first_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'groups': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['auth.Group']", 'symmetrical': 'False', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_staff': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_superuser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'last_login': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'last_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'password': ('django.db.models.fields.CharField', [], {'max_length': '128'}),
            'user_permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'}),
            'username': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '30'})
        },
        u'contenttypes.contenttype': {
            'Meta': {'ordering': "('name',)", 'unique_together': "(('app_label', 'model'),)", 'object_name': 'ContentType', 'db_table': "'django_content_type'"},
            'app_label': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'model': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        },
        u'controles.abandono': {
            'Meta': {'object_name': 'Abandono'},
            'cantidad': ('django.db.models.fields.IntegerField', [], {}),
            'comentario_int': ('django.db.models.fields.TextField', [], {}),
            'dia': ('django.db.models.fields.DateField', [], {}),
            'estado': ('django.db.models.fields.CharField', [], {'max_length': '6'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'inspector': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'+'", 'to': u"orm['controles.TipoUsuario']"}),
            'intercepcion': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['controles.Prod_Interceptable']", 'symmetrical': 'False'}),
            'kilos': ('django.db.models.fields.FloatField', [], {}),
            'medida_int': ('django.db.models.fields.CharField', [], {'max_length': '21'}),
            'numero': ('django.db.models.fields.IntegerField', [], {}),
            'probable_origen': ('django_countries.fields.CountryField', [], {'max_length': '2'}),
            'rip': ('django.db.models.fields.related.OneToOneField', [], {'to': u"orm['controles.Record_Intercepcion']", 'unique': 'True'}),
            'ubicacion': ('django.db.models.fields.CharField', [], {'max_length': '28'})
        },
        u'controles.acta_denuncia_citacion': {
            'Meta': {'object_name': 'Acta_Denuncia_Citacion'},
            'acta_retencion': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['controles.Acta_Retencion']", 'blank': 'True'}),
            'firma': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'hechos': ('django.db.models.fields.TextField', [], {}),
            'hora_citacion': ('django.db.models.fields.DateTimeField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'infractor': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'infractor_adc'", 'to': u"orm['controles.Pasajero']"}),
            'numero': ('django.db.models.fields.IntegerField', [], {'unique': 'True'}),
            'observaciones': ('django.db.models.fields.TextField', [], {}),
            'oficina_citacion': ('django.db.models.fields.CharField', [], {'max_length': '30'})
        },
        u'controles.acta_destruccion': {
            'Meta': {'object_name': 'Acta_Destruccion'},
            'acta_intercepcion': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['controles.Acta_Intercepcion']"}),
            'acta_retencion': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['controles.Acta_Retencion']"}),
            'desnaturalizacion': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'firma': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'inspector': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['controles.TipoUsuario']"}),
            'intercepcion': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['controles.Intercepcion']"}),
            'numero': ('django.db.models.fields.IntegerField', [], {'unique': 'True'}),
            'observaciones': ('django.db.models.fields.TextField', [], {}),
            'prod_desnaturalizacion': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'resolucion': ('django.db.models.fields.CharField', [], {'max_length': '15'})
        },
        u'controles.acta_devolucion_cites': {
            'Meta': {'object_name': 'Acta_Devolucion_Cites'},
            'cargo_receptor': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'causal': ('django.db.models.fields.TextField', [], {}),
            'especimen': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'+'", 'to': u"orm['controles.Especimen_Cites']"}),
            'fecha_devolucion': ('django.db.models.fields.DateField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'institucion_receptor': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'numero': ('django.db.models.fields.IntegerField', [], {'unique': 'True'}),
            'receptor': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'tenedor': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'tenedor_adci'", 'to': u"orm['controles.Pasajero']"})
        },
        u'controles.acta_incidente': {
            'Meta': {'object_name': 'Acta_Incidente'},
            'firma': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'incidente': ('django.db.models.fields.TextField', [], {}),
            'numero': ('django.db.models.fields.IntegerField', [], {'unique': 'True'}),
            'observaciones': ('django.db.models.fields.TextField', [], {}),
            'pasajero': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'pasajero_ai'", 'to': u"orm['controles.Pasajero']"})
        },
        u'controles.acta_inspeccion': {
            'Meta': {'object_name': 'Acta_Inspeccion'},
            'compania_aerea': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'fecha': ('django.db.models.fields.DateField', [], {}),
            'hora_estimada': ('django.db.models.fields.TimeField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'matricula': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'nombre_aeropuerto': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'numero': ('django.db.models.fields.IntegerField', [], {}),
            'observaciones': ('django.db.models.fields.TextField', [], {}),
            'origen': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'ruta': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'tipo_vuelo': ('django.db.models.fields.CharField', [], {'max_length': '9'}),
            'vuelo': ('django.db.models.fields.CharField', [], {'max_length': '10'})
        },
        u'controles.acta_intercepcion': {
            'Meta': {'object_name': 'Acta_Intercepcion'},
            'firma': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'inspector': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['controles.TipoUsuario']"}),
            'intercepcion': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['controles.Intercepcion']"}),
            'numero': ('django.db.models.fields.IntegerField', [], {'unique': 'True'})
        },
        u'controles.acta_postrecepcion': {
            'Meta': {'object_name': 'Acta_PostRecepcion'},
            'adc': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'agencia': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'animal_a_bordo': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'area_no_inspeccionada': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'arribo': ('django.db.models.fields.DateTimeField', [], {}),
            'basuras_fijas': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'basuras_hermeticas': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'basuras_tapadas': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'deficiencia_corregida': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'desembarco_basuras': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'desembarcos': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['controles.Desembarco_Barco']"}),
            'hombres_desembarcan': ('django.db.models.fields.IntegerField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'mantiene_sellos': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'monitoreo': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'motivo_adc': ('django.db.models.fields.TextField', [], {}),
            'mujeres_desembarcan': ('django.db.models.fields.IntegerField', [], {}),
            'nombre_nave': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'numero': ('django.db.models.fields.IntegerField', [], {}),
            'numero_animal': ('django.db.models.fields.IntegerField', [], {}),
            'numero_sellos': ('django.db.models.fields.IntegerField', [], {}),
            'observaciones': ('django.db.models.fields.TextField', [], {}),
            'prod_sellados_recepcion': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'productos_regulados': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['controles.Prod_Regulado']", 'symmetrical': 'False'}),
            'puerto_anterior': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'puerto_c_limantria': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'puerto_inspeccion': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'puerto_siguiente': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'recepcion': ('django.db.models.fields.DateTimeField', [], {}),
            'sellos_rotos': ('django.db.models.fields.TextField', [], {}),
            'sitio_atraque': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'solicitan_antecedentes': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'supervision_sag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'tipo_animal': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'transbordo_basuras': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'ubicacion_sellos': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'zarpe': ('django.db.models.fields.DateTimeField', [], {})
        },
        u'controles.acta_recepcion': {
            'Meta': {'object_name': 'Acta_Recepcion'},
            'agencia': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'animal_a_bordo': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'area_no_inspeccionada': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'arribo': ('django.db.models.fields.DateTimeField', [], {}),
            'basuras_fijas': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'basuras_hermeticas': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'basuras_tapadas': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'cert_fitosanitario': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'deficiencia_corregida': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'descensos': ('django.db.models.fields.IntegerField', [], {}),
            'desembarcos': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['controles.Desembarco_Barco']"}),
            'hombres_desembarcan': ('django.db.models.fields.IntegerField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'mujeres_desembarcan': ('django.db.models.fields.IntegerField', [], {}),
            'nombre_nave': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'numero': ('django.db.models.fields.IntegerField', [], {}),
            'numero_animal': ('django.db.models.fields.IntegerField', [], {}),
            'numero_sellos': ('django.db.models.fields.IntegerField', [], {}),
            'observaciones': ('django.db.models.fields.TextField', [], {}),
            'pasajeros_ingresan': ('django.db.models.fields.IntegerField', [], {}),
            'periodo_revision': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'productos_regulados': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['controles.Prod_Regulado']", 'symmetrical': 'False'}),
            'puerto_anterior': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'puerto_c_limantria': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'puerto_inspeccion': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'puerto_siguiente': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'recepcion': ('django.db.models.fields.DateTimeField', [], {}),
            'revision_listado_puertos': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'sitio_atraque': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'solicitan_antecedentes': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'tipo_animal': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'ubicacion_sellos': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'zarpe': ('django.db.models.fields.DateTimeField', [], {})
        },
        u'controles.acta_retencion': {
            'Meta': {'object_name': 'Acta_Retencion'},
            'desde': ('django.db.models.fields.DateField', [], {}),
            'hasta': ('django.db.models.fields.DateField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'intercepcion': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['controles.Intercepcion']"}),
            'lugar': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'motivo': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'numero': ('django.db.models.fields.IntegerField', [], {'unique': 'True'}),
            'observaciones': ('django.db.models.fields.TextField', [], {}),
            'tipo_envase': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        },
        u'controles.controlesfronterizos': {
            'Meta': {'object_name': 'ControlesFronterizos'},
            'codigo': ('django.db.models.fields.CharField', [], {'max_length': '8'}),
            'comuna': ('django.db.models.fields.CharField', [], {'max_length': '25'}),
            'horario_inicio': ('django.db.models.fields.TimeField', [], {'null': 'True'}),
            'horario_termino': ('django.db.models.fields.TimeField', [], {'null': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'inspectores': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['auth.User']", 'null': 'True', 'symmetrical': 'False'}),
            'latitud': ('django.db.models.fields.DecimalField', [], {'max_digits': '11', 'decimal_places': '8'}),
            'longitud': ('django.db.models.fields.DecimalField', [], {'max_digits': '11', 'decimal_places': '8'}),
            'nombre': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '30'}),
            'region': ('django.db.models.fields.CharField', [], {'max_length': '55'}),
            'turno': ('django.db.models.fields.CharField', [], {'max_length': '12'})
        },
        u'controles.cores': {
            'Meta': {'object_name': 'Cores'},
            'fecha': ('django.db.models.fields.DateField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'numero': ('django.db.models.fields.IntegerField', [], {})
        },
        u'controles.desembarco_barco': {
            'Meta': {'object_name': 'Desembarco_Barco'},
            'fecha': ('django.db.models.fields.DateTimeField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        u'controles.dia_ccff_aereo': {
            'Meta': {'object_name': 'Dia_CCFF_Aereo'},
            'acta_inspeccion': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['controles.Acta_Inspeccion']"}),
            'avion_carga_ffaa_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'avion_carga_ffaa_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'avion_carga_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'avion_carga_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'avion_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'avion_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'avion_pas_ffaa_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'avion_pas_ffaa_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'avioneta_ffaa_ingresada': ('django.db.models.fields.IntegerField', [], {}),
            'avioneta_ffaa_inspeccionada': ('django.db.models.fields.IntegerField', [], {}),
            'avioneta_ingresada': ('django.db.models.fields.IntegerField', [], {}),
            'avioneta_inspeccionada': ('django.db.models.fields.IntegerField', [], {}),
            'cites_entrada_fauna': ('django.db.models.fields.IntegerField', [], {}),
            'cites_entrada_flora': ('django.db.models.fields.IntegerField', [], {}),
            'cites_salida_fauna': ('django.db.models.fields.IntegerField', [], {}),
            'cites_salida_flora': ('django.db.models.fields.IntegerField', [], {}),
            'control_fronterizo': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['controles.ControlesFronterizos']"}),
            'declaran_no_no_traen': ('django.db.models.fields.IntegerField', [], {}),
            'declaran_no_si_traen': ('django.db.models.fields.IntegerField', [], {}),
            'declaran_si_si_traen': ('django.db.models.fields.IntegerField', [], {}),
            'fecha': ('django.db.models.fields.DateField', [], {}),
            'heli_ffaa_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'heli_ffaa_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'heli_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'heli_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'hombres_ingresados': ('django.db.models.fields.IntegerField', [], {}),
            'hombres_inspeccionados': ('django.db.models.fields.IntegerField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'inspector': ('django.db.models.fields.related.OneToOneField', [], {'to': u"orm['auth.User']", 'unique': 'True'}),
            'mujeres_ingresadas': ('django.db.models.fields.IntegerField', [], {}),
            'mujeres_inspeccionadas': ('django.db.models.fields.IntegerField', [], {}),
            'n_adc': ('django.db.models.fields.IntegerField', [], {}),
            'n_declaran': ('django.db.models.fields.IntegerField', [], {}),
            'solicitud_inspeccion': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['controles.Sol_Inspeccion']"})
        },
        u'controles.dia_ccff_maritimo': {
            'Meta': {'object_name': 'Dia_CCFF_Maritimo'},
            'acta_recepcion': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['controles.Acta_Recepcion']"}),
            'aviso_recalada_inicio': ('django.db.models.fields.IntegerField', [], {}),
            'aviso_recalada_termino': ('django.db.models.fields.IntegerField', [], {}),
            'cisterna_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'cisterna_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'cites_entrada_fauna': ('django.db.models.fields.IntegerField', [], {}),
            'cites_entrada_flora': ('django.db.models.fields.IntegerField', [], {}),
            'cites_salida_fauna': ('django.db.models.fields.IntegerField', [], {}),
            'cites_salida_flora': ('django.db.models.fields.IntegerField', [], {}),
            'contenedor_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'contenedor_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'control_fronterizo': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['controles.ControlesFronterizos']"}),
            'crucero_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'crucero_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'declaran_no_no_traen': ('django.db.models.fields.IntegerField', [], {}),
            'declaran_no_si_traen': ('django.db.models.fields.IntegerField', [], {}),
            'declaran_si_si_traen': ('django.db.models.fields.IntegerField', [], {}),
            'fecha': ('django.db.models.fields.DateField', [], {}),
            'guerra_ffaa_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'guerra_ffaa_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'hombres_ingresados': ('django.db.models.fields.IntegerField', [], {}),
            'hombres_inspeccionados': ('django.db.models.fields.IntegerField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'inspector': ('django.db.models.fields.related.OneToOneField', [], {'to': u"orm['auth.User']", 'unique': 'True'}),
            'instruccion_ffaa_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'instruccion_ffaa_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'mercante_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'mercante_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'mujeres_ingresadas': ('django.db.models.fields.IntegerField', [], {}),
            'mujeres_inspeccionadas': ('django.db.models.fields.IntegerField', [], {}),
            'n_adc': ('django.db.models.fields.IntegerField', [], {}),
            'n_declaran': ('django.db.models.fields.IntegerField', [], {}),
            'pas_carga_ffaa_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'pas_carga_ffaa_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'post_recepcion': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['controles.Acta_PostRecepcion']"}),
            'tanque_ffaa_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'tanque_ffaa_inspeccionado': ('django.db.models.fields.IntegerField', [], {})
        },
        u'controles.dia_ccff_terrestre': {
            'Meta': {'object_name': 'Dia_CCFF_Terrestre'},
            'auto_ffaa_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'auto_ffaa_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'bicicletas_ingresadas': ('django.db.models.fields.IntegerField', [], {}),
            'bicicletas_inspeccionadas': ('django.db.models.fields.IntegerField', [], {}),
            'bus_ffaa_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'bus_ffaa_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'bus_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'bus_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'camion_atingente_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'camion_atingente_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'camion_ffaa_at_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'camion_ffaa_at_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'camion_ffaa_no_at_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'camion_ffaa_no_at_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'camion_no_atingente_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'camion_no_atingente_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'cites_entrada_fauna': ('django.db.models.fields.IntegerField', [], {}),
            'cites_entrada_flora': ('django.db.models.fields.IntegerField', [], {}),
            'cites_salida_fauna': ('django.db.models.fields.IntegerField', [], {}),
            'cites_salida_flora': ('django.db.models.fields.IntegerField', [], {}),
            'control_fronterizo': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['controles.ControlesFronterizos']"}),
            'declaran_no_no_traen': ('django.db.models.fields.IntegerField', [], {}),
            'declaran_no_si_traen': ('django.db.models.fields.IntegerField', [], {}),
            'declaran_si_si_traen': ('django.db.models.fields.IntegerField', [], {}),
            'fecha': ('django.db.models.fields.DateField', [], {}),
            'hombres_ingresados': ('django.db.models.fields.IntegerField', [], {}),
            'hombres_inspeccionados': ('django.db.models.fields.IntegerField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'inspector': ('django.db.models.fields.related.OneToOneField', [], {'to': u"orm['auth.User']", 'unique': 'True'}),
            'moto_ingresada': ('django.db.models.fields.IntegerField', [], {}),
            'moto_inspeccionada': ('django.db.models.fields.IntegerField', [], {}),
            'mujeres_ingresadas': ('django.db.models.fields.IntegerField', [], {}),
            'mujeres_inspeccionadas': ('django.db.models.fields.IntegerField', [], {}),
            'n_adc': ('django.db.models.fields.IntegerField', [], {}),
            'n_declaran': ('django.db.models.fields.IntegerField', [], {}),
            'tren_carga_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'tren_carga_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'tren_pas_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'tren_pas_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'vehiculo_dipl_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'vehiculo_dipl_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'vehiculo_hum_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'vehiculo_hum_inspeccionado': ('django.db.models.fields.IntegerField', [], {}),
            'vehiculo_part_ingresado': ('django.db.models.fields.IntegerField', [], {}),
            'vehiculo_part_inspeccionado': ('django.db.models.fields.IntegerField', [], {})
        },
        u'controles.especimen_cites': {
            'Meta': {'object_name': 'Especimen_Cites'},
            'acta_intercepcion': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['controles.Acta_Intercepcion']"}),
            'cantidad': ('django.db.models.fields.IntegerField', [], {}),
            'estado_especimen': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'nombre_cientifico': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'nombre_comun': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'pais_procedencia': ('django.db.models.fields.CharField', [], {'max_length': '30'})
        },
        u'controles.intercepcion': {
            'Meta': {'object_name': 'Intercepcion'},
            'cantidad': ('django.db.models.fields.IntegerField', [], {}),
            'comentario_int': ('django.db.models.fields.TextField', [], {}),
            'estado': ('django.db.models.fields.CharField', [], {'max_length': '6'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'intercepcion': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['controles.Prod_Interceptable']", 'symmetrical': 'False'}),
            'kilos': ('django.db.models.fields.FloatField', [], {}),
            'medida_int': ('django.db.models.fields.CharField', [], {'max_length': '21'}),
            'numero': ('django.db.models.fields.IntegerField', [], {}),
            'pasajero': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['controles.Pasajero']"}),
            'rip': ('django.db.models.fields.related.OneToOneField', [], {'to': u"orm['controles.Record_Intercepcion']", 'unique': 'True'})
        },
        u'controles.orden_tratamiento': {
            'Meta': {'object_name': 'Orden_Tratamiento'},
            'fecha': ('django.db.models.fields.DateField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'numero': ('django.db.models.fields.IntegerField', [], {})
        },
        u'controles.pasajero': {
            'Meta': {'object_name': 'Pasajero'},
            'declara': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'fecha': ('django.db.models.fields.DateField', [], {}),
            'genero': ('django.db.models.fields.CharField', [], {'max_length': '9'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'inspector': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['auth.User']"}),
            'n_doc': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'nombres_apellidos': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'pais_origen': ('django_countries.fields.CountryField', [], {'max_length': '2'}),
            'proceso': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'prox_puerto': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'tipo_doc': ('django.db.models.fields.CharField', [], {'max_length': '19'}),
            'ubicacion': ('django.db.models.fields.CharField', [], {'max_length': '28'}),
            'ultimo_puerto': ('django.db.models.fields.CharField', [], {'max_length': '30'})
        },
        u'controles.prod_interceptable': {
            'Meta': {'object_name': 'Prod_Interceptable'},
            'categoria': ('django.db.models.fields.CharField', [], {'max_length': '8'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'subtipo': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'tipo': ('django.db.models.fields.CharField', [], {'max_length': '30'})
        },
        u'controles.prod_regulado': {
            'Meta': {'object_name': 'Prod_Regulado'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'kilogramos': ('django.db.models.fields.DecimalField', [], {'max_digits': '5', 'decimal_places': '2'}),
            'medida_adoptada': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'numero_muestra': ('django.db.models.fields.IntegerField', [], {}),
            'pais_origen': ('django_countries.fields.CountryField', [], {'max_length': '2'}),
            'producto': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'unidad_muestra': ('django.db.models.fields.CharField', [], {'max_length': '10'})
        },
        u'controles.record_intercepcion': {
            'Meta': {'object_name': 'Record_Intercepcion'},
            'folio_protocolo': ('django.db.models.fields.IntegerField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'kilos': ('django.db.models.fields.FloatField', [], {})
        },
        u'controles.sol_inspeccion': {
            'Meta': {'object_name': 'Sol_Inspeccion'},
            'compania_aerea': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'escala_dos': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'escala_uno': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'fecha': ('django.db.models.fields.DateField', [], {}),
            'hora_estimada': ('django.db.models.fields.TimeField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'matricula': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'numero': ('django.db.models.fields.IntegerField', [], {}),
            'observaciones': ('django.db.models.fields.TextField', [], {}),
            'origen': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'ruta': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'tipo_vuelo': ('django.db.models.fields.CharField', [], {'max_length': '9'}),
            'vuelo': ('django.db.models.fields.CharField', [], {'max_length': '10'})
        },
        u'controles.tipousuario': {
            'Meta': {'object_name': 'TipoUsuario'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'nombre': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'region': ('django.db.models.fields.CharField', [], {'max_length': '55'}),
            'tipo': ('django.db.models.fields.CharField', [], {'max_length': '4'}),
            'usuario': ('django.db.models.fields.related.OneToOneField', [], {'to': u"orm['auth.User']", 'unique': 'True'})
        },
        u'controles.turno': {
            'Meta': {'object_name': 'Turno'},
            'deteccion_ingreso': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'deteccion_prod_no_conf': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'dia_entrega': ('django.db.models.fields.DateTimeField', [], {}),
            'envio_ac_incidentes': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'envio_cites': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'envio_reclamos': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'envios_adc': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'funcionamiento_canina': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'funcionamiento_incin': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'funcionamiento_rx': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'inspectores': ('django.db.models.fields.related.ManyToManyField', [], {'related_name': "'+'", 'symmetrical': 'False', 'to': u"orm['controles.TipoUsuario']"}),
            'intercepcion_ampliada': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'jefe_turno': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'+'", 'to': u"orm['controles.TipoUsuario']"}),
            'llenado_furi': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'obs_adc': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'obs_cites': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'obs_deteccion': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'obs_func_canina': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'obs_func_incin': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'obs_func_rx': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'obs_incidentes': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'obs_ingreso': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'obs_intercepcion': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'obs_llenado': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'obs_no_eliminados': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'obs_proc_admin': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'obs_recepcion': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'obs_reclamos': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'proc_administrativo': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'prod_no_eliminados': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'recepcion_correos': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'sgte_jefe_turno': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'+'", 'to': u"orm['controles.TipoUsuario']"})
        }
    }

    complete_apps = ['controles']